### ISSUE TITLE
Rendering of gauge with maximum value over 100

### ISSUE THREAD

**Issue by Elkropac** [MCrissDev/Ariela#47]
Hi,
i have problem with rendering of gauge in lovelace ui.
It has max value of 2000, but i think, ariela renders it with max of 100, see screenshots attached

Thanks,
Libor

in Ariela
![Screenshot_20190501-184733_Ariela PRO](https://user-images.githubusercontent.com/28620417/57029552-620a6300-6c42-11e9-8f21-4cbc18bb8cac.jpg)

in homeassistant
![Screenshot_20190501_184823](https://user-images.githubusercontent.com/28620417/57029564-6cc4f800-6c42-11e9-82cc-695b2b96a7c2.png)

It has following code
```yaml
entity: sensor.neo_coolcam_unknown_type_0200_id_1027_power
max: 2000
min: 0
name: spotreba
severity:
  green: 0
  red: 1500
  yellow: 600
theme: Backend-selected
type: gauge
```

**Comment by MCrissDev** [comment]
Thank you for reporting the issue. I will fix it asap.

**Comment by MCrissDev** [comment]
Version 1.3.2.4 should fix the issue. Please update the app and let me know if works

**Comment by Elkropac** [comment]
Hi, thanks for new version.
I will have to wait till water in tank cools down :)

But it seems, it broke other gauges, top one is temperature defined in range 0-35 , bottom one is battery of my phone, defined in range 0-100

Libor
![Screenshot_20190502-143116_Ariela PRO](https://user-images.githubusercontent.com/28620417/57075553-63419b80-6ce7-11e9-9f0a-30f917130312.jpg)

**Comment by MCrissDev** [comment]
Hmm...can you share those cards configuration please?

**Comment by Elkropac** [comment]
Sure

top one: room temperature from zwave sensor
```yaml
entity: sensor.neo_coolcam_battery_powered_pir_sensor_v2_temperature
max: 35
min: 0
name: teplota
severity:
  green: 22
  red: 30
  yellow: 28
theme: default
type: gauge
```
bottom one (it has no severity set before i open yaml editor): phone battery from Ariela
```yaml
entity: sensor.lib_or_phn_battery_sensor
max: 100
min: 0
name: telefon
theme: default
type: gauge
severity:
  green: 0
  yellow: 0
  red: 0
```
