### ISSUE TITLE
Panel mode renders on half the screen

### ISSUE THREAD

**Issue by nervling** [MCrissDev/Ariela#99]
Using a rooted kindle fire HD8.

In my chrome browser in panel mode I see: https://imgur.com/pz5qCcP

However, in ariela lovelace UI it renders this way: https://imgur.com/ce6CA1G

I've tried changing the vertical/horizontal card settings, but that doesn't seem to help. Any ideas?

**Comment by MCrissDev** [comment]
Hi,

Can you share please that view configuration you are using so i can replicate it. Also please tell me the number of columns setting from Ariela. Thank you

**Comment by nervling** [comment]
Columns is set to auto.

```
cards:
  - cards:
      - entities:
          - entity: cover.bedroom_blind_1_level
          - entity: cover.bedroom_blind_2_level
          - entity: cover.bedroom_blind_3_level
          - entity: cover.bedroom_blind_4_level
          - entity: cover.bedroom_blind_5_level
          - entity: cover.bedroom_blind_6_level
        type: entities
      - cards:
          - entity: group.all_covers
            hold_action:
              action: more-info
            icon: 'mdi:arrow-up-box'
            name: Open Blinds
            show_icon: true
            show_name: true
            tap_action:
              action: call-service
              service: cover.open_cover
            type: entity-button
          - entity: group.all_covers
            hold_action:
              action: more-info
            icon: 'mdi:stop'
            name: Stop Blinds
            show_icon: true
            show_name: true
            tap_action:
              action: call-service
              service: cover.stop_cover
            type: entity-button
          - entity: group.all_covers
            hold_action:
              action: more-info
            icon: 'mdi:arrow-down-box'
            name: Close Blinds
            show_icon: true
            show_name: true
            tap_action:
              action: call-service
              service: cover.close_cover
            type: entity-button
        type: horizontal-stack
      - cards:
          - entity: light.jasco_products_14294_in_wall_smart_dimmer_level_3
            hold_action:
              action: more-info
            name: Fan
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: switch.master_bathroom_vanity
            hold_action:
              action: more-info
            icon: 'mdi:lightbulb'
            name: Bathroom Vanity
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
        type: horizontal-stack
    type: vertical-stack
  - cards:
      - cards:
          - entity: script.play_classic_rock
            hold_action:
              action: none
            icon: 'mdi:music-circle'
            name: Play Classic Rock
            show_icon: true
            show_name: true
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.play_classic_rock
            type: entity-button
          - entity: script.stop_music
            hold_action:
              action: none
            icon: 'mdi:music-circle'
            name: Stop Music
            show_icon: true
            show_name: true
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.stop_music
            type: entity-button
        type: horizontal-stack
      - entity: media_player.bedroom_speakers
        type: media-control
    type: vertical-stack
panel: true
type: horizontal-stack

```
